; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and devices
; https://docs.platformio.org/page/projectconf.html

[env:Main] 
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<main>
monitor_speed = 112500
lib_deps = 
	;pololu/VL53L0X@^1.3.1
	;mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8
	adafruit/Adafruit NeoPixel @ ^1.11.0
	z3t0/IRremote@^4.1.2

; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino
; build_src_filter = +<*> -<.git/> -<.svn/> -<devices>
; monitor_speed = 112500
; lib_deps = 
; 	pololu/VL53L0X@^1.3.1
; 	z3t0/IRremote@^4.1.2
; 	adafruit/Adafruit NeoPixel @ ^1.11.0
; 	mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8

[env:Devices-IR]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<devices/IR>
monitor_speed = 112500
lib_deps = 
	z3t0/IRremote@^4.1.2
	mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8

[env:Devices-LED]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<devices/LED_RGB>
monitor_speed = 112500
lib_deps = 
	adafruit/Adafruit NeoPixel @ ^1.11.0
	mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8

[env:Devices-QRE]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<devices/refletancia>
monitor_speed = 115200
lib_deps = mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8

[env:Devices-Jsumo]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<devices/JS40F_JSumo>
monitor_speed = 115200
	

[env:Devices-VLs]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<devices/VLs>
monitor_speed = 115200
lib_deps = 
	pololu/VL53L0X@^1.3.1
	mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8

[env:Devices-TB6612]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<devices/tb6612>
monitor_speed = 112500
lib_deps = mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8

[env:Devices-TB67H450]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<devices/tb67h450>
monitor_speed = 112500
lib_deps = mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8


[env:Fight-RE]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<fight/teste_re>
monitor_speed = 112500
lib_deps = mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8
		z3t0/IRremote@^4.1.2

[env:Fight-SEGUE_MAO]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<fight/Segue_mao> 
monitor_speed = 112500
lib_deps = 
	pololu/VL53L0X@^1.3.1
	mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8
	adafruit/Adafruit NeoPixel @ ^1.11.0
	z3t0/IRremote@^4.1.2

[env:Fight-ENEMY_TRACKER]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<fight/enemy_tracker> 
monitor_speed = 112500
lib_deps = 
	pololu/VL53L0X@^1.3.1
	mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8
	adafruit/Adafruit NeoPixel @ ^1.11.0
	z3t0/IRremote@^4.1.2

[env:Fight-MEIALUA]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<fight/meiaLua> 
monitor_speed = 112500
lib_deps = 
	pololu/VL53L0X@^1.3.1
	mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8
	adafruit/Adafruit NeoPixel @ ^1.11.0
	z3t0/IRremote@^4.1.2

[env:iron_noCore] 
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<fight/iron_noCore>
monitor_speed = 115200
lib_deps = 
	;pololu/VL53L0X@^1.3.1
	;mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8
	adafruit/Adafruit NeoPixel @ ^1.11.0
	z3t0/IRremote@^4.1.2
	# Accept new functionality in a backwards compatible manner and patches
  	madhephaestus/ESP32Servo @ ^3.0.6

[env:RSM_Iron] 
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<fight/RSM_iron>
monitor_speed = 115200
lib_deps = 
	;pololu/VL53L0X@^1.3.1
	;mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8
	adafruit/Adafruit NeoPixel @ ^1.11.0
	z3t0/IRremote@^4.1.2
	# Accept new functionality in a backwards compatible manner and patches
  	madhephaestus/ESP32Servo @ ^3.0.6

[env:MPU_fight] 
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<fight/mpu>
monitor_speed = 115200
lib_deps = 
	;pololu/VL53L0X@^1.3.1
	;mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8
	adafruit/Adafruit NeoPixel @ ^1.11.0
	z3t0/IRremote@^4.1.2
	# Accept new functionality in a backwards compatible manner and patches
  	madhephaestus/ESP32Servo @ ^3.0.6
	# Accept new functionality in a backwards compatible manner and patches
  	adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.9
    Wire

[env:mpu]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<devices/mpu>
monitor_speed = 115200
lib_deps =
    # Accept new functionality in a backwards compatible manner and patches
  	adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.9
    Wire


[env:Devices-Servo]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<devices/servo>
monitor_speed = 115200
lib_deps = 
	z3t0/IRremote@^4.1.2
	# Accept new functionality in a backwards compatible manner and patches
  	madhephaestus/ESP32Servo @ ^3.0.6
